name: Black code style check

on: [push]

jobs:
  black:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: Install apt dependencies
      run: |
        sudo apt-get update && sudo apt-get install python3 python3-pip -y
    - name: Install pip dependencies
      run: |
        pip3 install black
    - name: Check code style with Black
      run: |
        black --check --diff --line-length 79 .
